# fly.toml app configuration file generated for icon-rhizome-dev on 2023-04-26T20:07:50+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "icon-rhizome-dev"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.http_check]
    grace_period = "8s"
    interval = "2s"
    method = "get"
    path = "/"
    port = 8080
    timeout = "5s"
    type = "http"
    
[[statics]]
  guest_path = "/icon_rhizome_dev/static"
  url_prefix = "/static"